export const hyperlink = {
    recommendation: {
        title: '强烈推荐',
        jumpLink: [
            {linkCh: 'PDF派', linkWeb: 'https://www.pdfpai.com/'},
            {linkCh: '奶牛快传', linkWeb: 'https://cowtransfer.com/'},
            {linkCh: '鸠摩搜索', linkWeb: 'https://www.jiumodiary.com/'},
            {linkCh: 'Zlibrary', linkWeb: 'https://zh.zlib.life/'},
            {linkCh: '荐片播放器', linkWeb: 'https://www.jianpian9.com/'},
            {linkCh: 'free影视', linkWeb: 'http://app.free52.com/'},
            {linkCh: '哔哩哔哩', linkWeb: 'https://www.bilibili.com/'},
            {linkCh: '优优教程网', linkWeb: 'https://uiiiuiii.com/'},
            {linkCh: 'w3school', linkWeb: 'https://www.w3school.com.cn/'},
            {linkCh: 'Boss直聘', linkWeb: 'https://www.zhipin.com/'},
            {linkCh: '智联招聘', linkWeb: 'https://www.zhaopin.com/'},
            {linkCh: '美团酒店红包', linkWeb: '/#/meiTuanHotelPacket'},
            {linkCh: '美团外卖红包', linkWeb: '/#/meiTuanPacket'},
            {linkCh: '饿了么红包', linkWeb: '/#/eLeMePacket'},
            {linkCh: '支付宝红包', linkWeb: 'https://mp.weixin.qq.com/s/UpvEHUEzdoCuwjqllCLc0g'},
            {linkCh: '省钱APP', linkWeb: 'https://mp.weixin.qq.com/s/smyndm9RkhsEagbErRxAMQ'},
        ],
    },
    tools: {
        title: '实用工具',
        jumpLink: [
            {linkCh: 'ProcessOn', linkWeb: 'https://www.processon.com/'},
            {linkCh: 'TinyPNG', linkWeb: 'https://tinypng.com/'},
            {linkCh: 'removebg', linkWeb: 'https://www.remove.bg/zh'},
            {linkCh: 'musetransfer', linkWeb: 'https://musetransfer.com/'},
            {linkCh: '奶牛快传', linkWeb: 'https://cowtransfer.com/'},
            {linkCh: '幕布', linkWeb: 'https://mubu.com/home'},
            {linkCh: 'PDF派', linkWeb: 'https://www.pdfpai.com/'},
            {linkCh: '爱给网', linkWeb: 'https://www.aigei.com/'},
            {linkCh: '即使工具', linkWeb: 'https://www.67tool.com/'},
        ],
    },
    reading: {
        title: '阅读小说',
        jumpLink: [
            {linkCh: '鸠摩搜索', linkWeb: 'https://www.jiumodiary.com/'},
            {linkCh: 'Zlibrary', linkWeb: 'https://zh.zlib.life/'},
            {linkCh: '书格', linkWeb: 'https://new.shuge.org/'},
            {linkCh: '苦瓜书盘', linkWeb: 'http://www.kgbook.com/'},
            {linkCh: '超星读书', linkWeb: 'http://book.chaoxing.com/'},
            {linkCh: '熊猫搜书', linkWeb: 'https://xmsoushu.com/#/'},
            {linkCh: '书舟搜索', linkWeb: 'https://www.shuzhou.cc/'},
            {linkCh: '书单网', linkWeb: 'https://www.shudan.vip/'},
            {linkCh: '书享家', linkWeb: 'http://www.shuxiangjia.cn/'},
            {linkCh: '盘搜搜', linkWeb: 'https://www.pansoso.com/'},
            {linkCh: '书栈网', linkWeb: 'https://www.bookstack.cn/'},
            {linkCh: '图灵社区', linkWeb: 'https://www.ituring.com.cn/'},
        ],
    },
    movies: {
        title: '影视娱乐',
        jumpLink: [
            {linkCh: '555电影', linkWeb: 'https://www.5dy6.vip/'},
            {linkCh: '真不卡影院', linkWeb: 'https://www.zhenbuka5.com/'},
            {linkCh: '追剧达人', linkWeb: 'http://vipmv.tv/'},
            {linkCh: 'TV1920', linkWeb: 'https://www.tv1920.com/'},
            {linkCh: '天空影视', linkWeb: 'https://www.tkys.tv/'},
            {linkCh: '火火影视', linkWeb: 'https://www.huohuo99.com/'},
            {linkCh: '快猫影视', linkWeb: 'https://www.maomiava.com/'},
            {linkCh: '荐片播放器', linkWeb: 'https://www.jianpian9.com/'},
            {linkCh: 'free影视', linkWeb: 'http://app.free52.com/'},
        ],
    },
    courses: {
        title: '课程学习',
        jumpLink: [
            {linkCh: '中国大学MOOC', linkWeb: 'https://www.icourse163.org/'},
            {linkCh: '大学资源网', linkWeb: 'http://www.dxzy163.com/'},
            {linkCh: '网易云课堂', linkWeb: 'https://study.163.com/'},
            {linkCh: '网易公开课', linkWeb: 'https://open.163.com/'},
            {linkCh: '哔哩哔哩', linkWeb: 'https://www.bilibili.com/'},
            {linkCh: '学堂在线', linkWeb: 'https://www.xuetangx.com/'},
            {linkCh: '超星尔雅', linkWeb: 'http://erya.mooc.chaoxing.com/'},
            {linkCh: '好知网', linkWeb: 'http://www.howzhi.com/'},
            {linkCh: '泸江', linkWeb: 'https://www.hujiang.com/'},
        ],
    },
    design: {
        title: '设计类',
        jumpLink: [
            {linkCh: '优优教程网', linkWeb: 'https://uiiiuiii.com/'},
            {linkCh: '巧匠课堂', linkWeb: 'https://www.2qj.com/'},
            {linkCh: '蓝铅笔', linkWeb: 'https://www.lanqb.com/'},
            {linkCh: '高高手', linkWeb: 'https://www.gogoup.com/'},
            {linkCh: '花瓣', linkWeb: 'https://huaban.com/'},
            {linkCh: '学UI网', linkWeb: 'https://www.xueui.cn/'},
            {linkCh: 'doyoudo', linkWeb: 'https://www.doyoudo.com/free'},
        ],
    },
    programming: {
        title: '编程类',
        jumpLink: [
            {linkCh: '菜鸟教程', linkWeb: 'https://www.runoob.com/'},
            {linkCh: 'w3school', linkWeb: 'https://www.w3school.com.cn/'},
            {linkCh: '慕课网', linkWeb: 'https://www.imooc.com/'},
            {linkCh: '夜曲编程', linkWeb: 'https://np.baicizhan.com/'},
            {linkCh: '掘金', linkWeb: 'https://juejin.cn/'},
            {linkCh: '博客园', linkWeb: 'https://www.cnblogs.com/'},
            {linkCh: 'ZDZN', linkWeb: 'https://www.zdzn.net/'},
            {linkCh: 'CSDN', linkWeb: 'https://www.csdn.net/'},
            {linkCh: '牛客网', linkWeb: 'https://www.nowcoder.com/'},
            {linkCh: 'LeetCode', linkWeb: 'https://leetcode.cn/'},
            {linkCh: 'GitHub', linkWeb: 'https://github.com/'},
        ],
    },
    language: {
        title: '语言类',
        jumpLink: [
            {linkCh: 'TED', linkWeb: 'https://www.ted.com/'},
            {linkCh: 'YouZack', linkWeb: 'https://www.youzack.com/'},
            {linkCh: '多邻国', linkWeb: 'https://www.duolingo.cn/learn'},
            {linkCh: '译学馆', linkWeb: 'https://www.yxgapp.com/'},
            {linkCh: '沪江英语网', linkWeb: 'https://www.hjenglish.com/'},
            {linkCh: '有道精品课', linkWeb: 'https://ke.youdao.com/'},
            {linkCh: '声同小语种', linkWeb: 'http://www.somdom.com/'},
        ]
    },
    Recruitment: {
        title: '招聘信息',
        jumpLink: [
            {linkCh: 'Boss直聘', linkWeb: 'https://www.zhipin.com/'},
            {linkCh: '猎聘', linkWeb: 'https://www.liepin.com/'},
            {linkCh: '前程无忧', linkWeb: 'https://www.51job.com/'},
            {linkCh: '智联招聘', linkWeb: 'https://www.zhaopin.com/'},
            {linkCh: '拉勾招聘', linkWeb: 'https://www.lagou.com/'},
            {linkCh: '应届生求职网', linkWeb: 'http://www.yingjiesheng.com/'},
            {linkCh: '职未来', linkWeb: 'http://www.careerol.com/'},
            {linkCh: '海投网', linkWeb: 'https://www.haitou.cc/'},
            {linkCh: '实习僧', linkWeb: 'https://www.shixiseng.com/'},
            {linkCh: '刺猬实习', linkWeb: 'https://www.ciwei.net/'},
        ]
    },

}